from typing import Dict, Any, Callable, List
from utils.observer import Observable
from utils.config_manager import config_manager
import json
import os

class LanguageManager:
    """语言管理器类"""
    
    def __init__(self):
        """初始化语言管理器"""
        self._current_language = "zh"
        self._callbacks = []
        self._translations = {
            "zh": {},
            "en": {},
            "de": {}
        }
        self._load_translations()
        
    def _load_translations(self):
        """加载翻译数据"""
        # 中文翻译
        self._translations["zh"].update({
            "app_title": "ZK-Bom逻辑配置器",   
            "confirm": "确认",
            "cancel": "取消",
            "error": "错误",
            "warning": "警告",
            "info": "信息",
            "menu_file": "文件",
            "menu_view": "视图",
            "menu_help": "帮助",
            "import_config": "导入配置",
            "import_bom": "导入BOM",
            "logic_library": "逻辑关系库",
            "language": "语言",
            "theme": "主题",
            "view_log": "查看日志",
            "about": "关于",
            "exit": "退出",
            "panels_title": "ZK逻辑编辑器",
            "config_panel_title": "配置选项",
            "logic_panel_title": "逻辑编辑",
            "bom_panel_title": "BOM管理",
            "tools": "工具栏",
            "refresh": "刷新",
            "clear": "清除",
            "save": "保存",
            "logic_operators": "逻辑操作符",
            "brackets": "括号",
            "rule_status": "规则状态",
            "enabled": "启用",
            "disabled": "禁用",
            "testing": "测试",
            "expression": "表达式",
            "saved_rules": "已保存规则",
            "config_tree": "配置树",
            "bom_tree": "BOM树",
            "search": "搜索",
            "rules": "规则",
            "rule_id": "规则ID",
            "rule_type": "规则类型",
            "condition": "选择项表达式",
            "effect": "影响项表达式",
            "status": "状态",
            "light_theme": "浅色主题",
            "dark_theme": "深色主题",
            "ready": "就绪",
            "copy_code": "复制代码",
            "copy_item": "复制项目",
            "edit": "编辑",
            "delete": "删除",
            "select_excel_file": "选择Excel文件",
            "select_bom_file": "选择BOM文件",
            "excel_files": "Excel文件",
            "all_files": "所有文件",
            "confirm_exit": "确认退出",
            "confirm_exit_message": "确定要退出程序吗？",
            "excel_imported_successfully": "Excel文件导入成功",
            "bom_imported_successfully": "BOM文件导入成功",
            "excel_import_error": "导入Excel文件失败",
            "bom_import_error": "导入BOM文件失败",
            "refresh_tree_error": "刷新树状图失败",
            "open_log_error": "打开日志文件失败",
            "theme_dialog_title": "选择主题",
            "theme_dialog_header": "请选择主题",
            "refresh_tree": "刷新树状图",
            "clear_expression": "清除表达式",
            "save_rule": "保存规则",
            "delete_last": "删除上一个",
            "clear_all": "清除全部",
            "error_must_start_with_k": "表达式必须以K码开头",
            "error_bom_before_implication": "在→出现之前不能插入BOM码",
            "error_k_after_implication": "在→之后不能插入K码",
            "error_invalid_operator_sequence": "K码之间必须用AND、OR、AND NOT或OR NOT连接",
            "error_invalid_bracket": "括号使用不正确",
            "error_invalid_token": "无效的输入",
            "empty_expression": "表达式不能为空",
            "missing_implication_operator": "缺少蕴含操作符 →",
            "empty_left_expression": "→ 左侧表达式不能为空",
            "empty_right_expression": "→ 右侧表达式不能为空",
            "left_expression_error": "→ 左侧表达式错误",
            "right_expression_error": "→ 右侧表达式错误",
            "not_operator_error": "NOT 操作符使用错误",
            "parentheses_mismatch": "括号不匹配",
            "invalid_bool_expression": "无效的布尔表达式",
            "error_consecutive_codes": "不能连续插入两个代码，必须使用操作符连接",
            "expression_ends_with_operator": "表达式不能以操作符结尾",
            "invalid_first_token": "表达式必须以左括号、NOT或K码开头",
            "invalid_token_after_operator": "操作符后面只能跟左括号、NOT或变量",
            "invalid_token_after_not": "NOT后面只能跟左括号或变量",
            "invalid_token_after_left_parenthesis": "左括号后面只能跟左括号、NOT或变量",
            "invalid_token_after_right_parenthesis": "右括号后面只能跟右括号、AND、OR或→",
            "invalid_token_after_k_code": "K码后面只能跟右括号、AND、OR或→",
            "invalid_token_after_implication": "→后面只能跟左括号、NOT或BOM码",
            "invalid_token_after_bom_code": "BOM码后面只能跟右括号、AND或OR",
            "invalid_expression_state": "无效的表达式状态",
            "error_consecutive_operators": "操作符不能连续使用",
            "load_last_config_confirm": "是否加载上次的配置文件？",
            "load_last_bom_confirm": "是否加载上次的BOM文件？",
            "load_last_config_error": "加载上次配置文件失败",
            "load_last_bom_error": "加载上次BOM文件失败",
            "update_display_error": "更新显示失败",
            "success": "成功",
            "success_title": "成功",
            "import_config_success": "配置文件导入成功",
            "import_bom_success": "BOM文件导入成功",
            "error_title": "错误",
            "warning_title": "警告",
            "confirm_title": "确认",
            "error_invalid_before_k": "K码前面必须是左括号、AND、OR或NOT",
            "error_invalid_before_bom": "BOM码前面必须是→、左括号、AND、OR或NOT",
            "error_invalid_first_input": "表达式必须以K码、左括号或NOT开头",
            "error_invalid_sequence": "输入顺序不正确，请检查逻辑表达式规则",
            "error_unmatched_parentheses": "括号不匹配，请检查左右括号数量",
            "error_consecutive_not": "NOT操作符不能连续使用",
            "error_consecutive_left_parentheses": "左括号之间必须有其他内容",
            "error_consecutive_right_parentheses": "右括号之间必须有其他内容",
            "error_empty_parentheses": "括号内必须有内容",
            "error_parentheses_after_not": "NOT后面不能直接跟右括号",
            "error_operator_before_right_parenthesis": "右括号前不能是操作符",
            "error_missing_left_parenthesis": "缺少对应的左括号",
            "error_missing_right_parenthesis": "缺少对应的右括号",
            "error_invalid_after_operator": "操作符后面必须是K码、BOM码、NOT或左括号",
            "error_invalid_before_operator": "操作符前面必须是K码、BOM码或右括号",
            "error_invalid_after_not": "NOT后面必须是K码、BOM码或左括号",
            "error_invalid_after_left_parenthesis": "左括号后面必须是K码、NOT或左括号",
            "error_invalid_before_right_parenthesis": "右括号前面必须是K码、BOM码或右括号",
            "error_invalid_before_implication": "蕴含符号(→)前面必须是K码或右括号",
            "error_multiple_implications": "表达式中只能有一个蕴含符号(→)",
            "error_invalid_after_variable": "变量后面只能跟右括号、AND、OR或→",
            "error_validation_failed": "表达式验证失败，请检查输入",
            "error_invalid_before_left_parenthesis": "左括号前面必须是AND、OR、NOT或→",
            "error_invalid_before_right_parenthesis": "右括号前面必须是K码、BOM码或右括号",
            "error_invalid_before_operator": "操作符前面必须是K码、BOM码或右括号",
            "error_invalid_before_implication": "蕴含符号(→)前面必须是K码或右括号",
            "error_invalid_before_not": "NOT前面不能是变量或右括号",
            "error_implication_at_start": "表达式不能以蕴含符号(→)开始",
            "error_empty_expression": "表达式不能为空",
            "error_missing_implication": "请先输入基本逻辑表达式，包含→符号",
            "error_invalid_expression_format": "表达式格式无效",
            "error_saving_rule": "保存规则时出错",
            "rule_saved_successfully": "规则保存成功",
            "edit_rule": "编辑逻辑规则",
            "edit_rule_condition": "选择项表达式",
            "edit_rule_effect": "影响项表达式",
            "edit_rule_status": "规则状态",
            "export_logic_rules": "导出BOM逻辑关系",
            "load_last_rules_confirm": "检测到上次有未导出的BOM逻辑关系，是否加载？",
            "unsaved_rules_exit_confirm": "检测到还有未导出的BOM逻辑关系，确定要退出吗？",
            "export_rules_success": "BOM逻辑关系导出成功",
            "export_rules_error": "BOM逻辑关系导出失败",
            "select_export_file": "选择导出文件位置",
            "json_files": "JSON文件",
            "rules_deleted": "未保存的BOM逻辑关系已删除",
            "import_logic_rules": "导入BOM逻辑关系",
            "select_import_file": "选择导入文件",
            "import_rules_success": "BOM逻辑关系导入成功",
            "import_rules_error": "BOM逻辑关系导入失败",
            "unsaved_rules_import_confirm": "检测到有未导出的BOM逻辑关系，导入新的规则将清空当前规则，是否继续？",
            "unsaved_rules_warning": "有未导出的BOM逻辑关系",
            "temp_rules_loaded": "已加载临时保存的BOM逻辑关系",
            "temp_rules_not_found": "未找到临时保存的BOM逻辑关系",
            "temp_rules_load_error": "加载临时保存的BOM逻辑关系失败",
            "temp_rules_save_success": "BOM逻辑关系已临时保存",
            "temp_rules_save_error": "临时保存BOM逻辑关系失败",
            "confirm_delete_rule": "确定要删除这条规则吗？",
            "feature_value": "特征值",
            "feature_code": "特征",
            "feature_value_name": "特征值名称",
            "feature_code_format": "特征码格式：HBG_xxx_xxxxx",
            "feature_value_format": "特征值格式：K-xxx-xxxxxx",
            "rule_tags": "标签",
            "tech_doc": "技术文档",
            "edit_tags": "编辑标签",
            "input_tags": "请输入标签（多个标签用逗号分隔）",
            "select_tech_doc": "选择技术文档",
            "word_files": "Word文档",
            "tech_doc_added_success": "技术文档添加成功",
            "import_tech_doc": "导入技术文档",
            "open_tech_doc_error": "打开技术文档失败，请确认文件存在且可以访问",
            "adjust_logic": "微调逻辑",
            "on": "当",
            "add": "添加",
            "from": "从",
            "change_quantity_of": "修改数量从",
            "to": "到",
            "change_price": "修改价格",
            "insert": "插入",
            "error_multiple_tuning_logic": "一个表达式只能包含一个微调逻辑",
            "error_incomplete_on_add": "请输入完整的ON ADD值",
            "error_incomplete_from_delete": "请输入完整的FROM DELETE值",
            "error_incomplete_change_quantity": "请输入完整的CHANGE QUANTITY值",
            "error_invalid_price_format": "价格必须以+或-开头，后跟数字",
            "export_and_clear_success": "规则已成功导出，暂存数据已删除",
            "search_and_filter": "搜索与筛选",
            "logic_type_filter": "逻辑类型",
            "all_logics": "所有逻辑",
            "bom_logic": "BOM逻辑",
            "tuning_logic": "微调逻辑",
            "logic_status_filter": "逻辑状态",
            "all_statuses": "所有状态",
            "search_condition": "搜索条件",
            "search_effect": "搜索影响",
            "search_tags": "搜索标签",
            "clear_all_filters": "清除所有筛选",
            "search_bom_code": "搜索BOM码",
            "search_feature_or_k": "搜索特征码(HBG码)或特征值(K码)",
            "code_not_found": "未找到匹配的特征码或特征值",
            "export_descriptions": "导出描述行",
            "descriptions_exported_successfully": "描述行导出成功",
            "export_descriptions_error": "导出描述行失败",
            "description": "描述"
        })
        
        # 英文翻译
        self._translations["en"].update({
            "app_title": "ZK Logic Editor",
            "confirm": "Confirm",
            "cancel": "Cancel",
            "error": "Error",
            "warning": "Warning",
            "info": "Information",
            "menu_file": "File",
            "menu_view": "View",
            "menu_help": "Help",
            "import_config": "Import Config",
            "import_bom": "Import BOM",
            "logic_library": "Logic Library",
            "language": "Language",
            "theme": "Theme",
            "view_log": "View Log",
            "about": "About",
            "exit": "Exit",
            "panels_title": "ZK Logic Editor",
            "config_panel_title": "Configuration",
            "logic_panel_title": "Logic Editor",
            "bom_panel_title": "BOM Management",
            "tools": "Toolbar",
            "refresh": "Refresh",
            "clear": "Clear",
            "save": "Save",
            "logic_operators": "Logic Operators",
            "brackets": "Brackets",
            "rule_status": "Rule Status",
            "enabled": "Enabled",
            "disabled": "Disabled",
            "testing": "Testing",
            "expression": "Expression",
            "saved_rules": "Saved Rules",
            "config_tree": "Config Tree",
            "bom_tree": "BOM Tree",
            "search": "Search",
            "rules": "Rules",
            "rule_id": "Rule ID",
            "rule_type": "Rule Type",
            "condition": "Selection Expression",
            "effect": "Impact Expression",
            "status": "Status",
            "light_theme": "Light Theme",
            "dark_theme": "Dark Theme",
            "ready": "Ready",
            "copy_code": "Copy Code",
            "copy_item": "Copy Item",
            "edit": "Edit",
            "delete": "Delete",
            "select_excel_file": "Select Excel File",
            "select_bom_file": "Select BOM File",
            "excel_files": "Excel Files",
            "all_files": "All Files",
            "confirm_exit": "Confirm Exit",
            "confirm_exit_message": "Are you sure you want to exit?",
            "excel_imported_successfully": "Excel file imported successfully",
            "bom_imported_successfully": "BOM file imported successfully",
            "excel_import_error": "Failed to import Excel file",
            "bom_import_error": "Failed to import BOM file",
            "refresh_tree_error": "Failed to refresh tree",
            "open_log_error": "Failed to open log file",
            "theme_dialog_title": "Select Theme",
            "theme_dialog_header": "Please select a theme",
            "refresh_tree": "Refresh Tree",
            "clear_expression": "Clear Expression",
            "save_rule": "Save Rule",
            "delete_last": "Delete Last",
            "clear_all": "Clear All",
            "error_must_start_with_k": "Expression must start with K code",
            "error_bom_before_implication": "Cannot insert BOM code before →",
            "error_k_after_implication": "Cannot insert K code after →",
            "error_invalid_operator_sequence": "K codes must be connected by AND, OR, AND NOT, or OR NOT",
            "error_invalid_bracket": "Invalid bracket usage",
            "error_invalid_token": "Invalid input",
            "empty_expression": "Expression cannot be empty",
            "missing_implication_operator": "Missing implication operator →",
            "empty_left_expression": "Left expression before → cannot be empty",
            "empty_right_expression": "Right expression after → cannot be empty",
            "left_expression_error": "Error in left expression before →",
            "right_expression_error": "Error in right expression after →",
            "not_operator_error": "Invalid use of NOT operator",
            "parentheses_mismatch": "Mismatched parentheses",
            "invalid_bool_expression": "Invalid boolean expression",
            "error_consecutive_codes": "Cannot insert two codes consecutively, must use operators between them",
            "expression_ends_with_operator": "Expression cannot end with an operator",
            "invalid_first_token": "Expression must start with left parenthesis, NOT, or K code",
            "invalid_token_after_operator": "Operator must be followed by left parenthesis, NOT, or variable",
            "invalid_token_after_not": "NOT must be followed by left parenthesis or variable",
            "invalid_token_after_left_parenthesis": "Left parenthesis must be followed by left parenthesis, NOT, or variable",
            "invalid_token_after_right_parenthesis": "Right parenthesis must be followed by right parenthesis, AND, OR, or →",
            "invalid_token_after_k_code": "K code must be followed by right parenthesis, AND, OR, or →",
            "invalid_token_after_implication": "→ must be followed by left parenthesis, NOT, or BOM code",
            "invalid_token_after_bom_code": "BOM code must be followed by right parenthesis, AND, or OR",
            "invalid_expression_state": "Invalid expression state",
            "error_consecutive_operators": "Operators cannot be used consecutively",
            "load_last_config_confirm": "Load the last configuration file?",
            "load_last_bom_confirm": "Load the last BOM file?",
            "load_last_config_error": "Failed to load last configuration file",
            "load_last_bom_error": "Failed to load last BOM file",
            "update_display_error": "Failed to update display",
            "success": "Success",
            "success_title": "Success",
            "import_config_success": "Configuration file imported successfully",
            "import_bom_success": "BOM file imported successfully",
            "error_title": "Error",
            "warning_title": "Warning",
            "confirm_title": "Confirm",
            "error_invalid_before_k": "K code must be preceded by left parenthesis, AND, OR, or NOT",
            "error_invalid_before_bom": "BOM code must be preceded by →, left parenthesis, AND, OR, or NOT",
            "error_invalid_first_input": "Expression must start with K code, left parenthesis, or NOT",
            "error_invalid_sequence": "Invalid input sequence, please check logic expression rules",
            "error_unmatched_parentheses": "Unmatched parentheses, please check the number of left and right parentheses",
            "error_consecutive_not": "NOT operators cannot be used consecutively",
            "error_consecutive_left_parentheses": "Left parentheses must be separated by other content",
            "error_consecutive_right_parentheses": "Right parentheses must be separated by other content",
            "error_empty_parentheses": "Parentheses cannot be empty",
            "error_parentheses_after_not": "Right parenthesis cannot follow NOT directly",
            "error_operator_before_right_parenthesis": "Right parenthesis cannot follow an operator",
            "error_missing_left_parenthesis": "Missing corresponding left parenthesis",
            "error_missing_right_parenthesis": "Missing corresponding right parenthesis",
            "error_invalid_after_operator": "Operator must be followed by K code, BOM code, NOT, or left parenthesis",
            "error_invalid_before_operator": "Operator must be preceded by K code, BOM code, or right parenthesis",
            "error_invalid_after_not": "NOT must be followed by K code, BOM code, or left parenthesis",
            "error_invalid_after_left_parenthesis": "Left parenthesis must be followed by K code, NOT, or left parenthesis",
            "error_invalid_before_right_parenthesis": "Right parenthesis must be preceded by K code, BOM code, or right parenthesis",
            "error_invalid_before_implication": "Implication operator (→) must be preceded by K code or right parenthesis",
            "error_multiple_implications": "Expression can only have one implication operator (→)",
            "error_invalid_after_variable": "Variable must be followed by right parenthesis, AND, OR, or →",
            "error_validation_failed": "Expression validation failed, please check your input",
            "error_invalid_before_left_parenthesis": "Left parenthesis must be preceded by AND, OR, NOT, or →",
            "error_invalid_before_right_parenthesis": "Right parenthesis must be preceded by K code, BOM code, or right parenthesis",
            "error_invalid_before_operator": "Operator must be preceded by K code, BOM code, or right parenthesis",
            "error_invalid_before_implication": "Implication operator (→) must be preceded by K code or right parenthesis",
            "error_invalid_before_not": "NOT cannot be preceded by a variable or right parenthesis",
            "error_implication_at_start": "Expression cannot start with implication operator (→)",
            "error_empty_expression": "Expression cannot be empty",
            "error_missing_implication": "Please enter a basic logic expression with → symbol first",
            "error_invalid_expression_format": "Invalid expression format",
            "error_saving_rule": "Error saving rule",
            "rule_saved_successfully": "Rule saved successfully",
            "edit_rule": "Edit Logic Rule",
            "edit_rule_condition": "Selection Expression",
            "edit_rule_effect": "Impact Expression",
            "edit_rule_status": "Rule Status",
            "export_logic_rules": "Export BOM Logic Rules",
            "load_last_rules_confirm": "Detected unexported BOM logic rules from last session, load them?",
            "unsaved_rules_exit_confirm": "There are unexported BOM logic rules, are you sure to exit?",
            "export_rules_success": "BOM logic rules exported successfully",
            "export_rules_error": "Failed to export BOM logic rules",
            "select_export_file": "Select export file location",
            "json_files": "JSON Files",
            "rules_deleted": "Unsaved BOM logic rules have been deleted",
            "import_logic_rules": "Import BOM Logic Rules",
            "select_import_file": "Select Import File",
            "import_rules_success": "BOM logic rules imported successfully",
            "import_rules_error": "Failed to import BOM logic rules",
            "unsaved_rules_import_confirm": "Detected unexported BOM logic rules, importing new rules will clear current rules, continue?",
            "unsaved_rules_warning": "There are unexported BOM logic rules",
            "temp_rules_loaded": "Temporarily saved BOM logic rules loaded",
            "temp_rules_not_found": "No temporarily saved BOM logic rules found",
            "temp_rules_load_error": "Failed to load temporarily saved BOM logic rules",
            "temp_rules_save_success": "BOM logic rules temporarily saved",
            "temp_rules_save_error": "Failed to temporarily save BOM logic rules",
            "confirm_delete_rule": "Are you sure you want to delete this rule?",
            "feature_value": "Feature Value",
            "feature_code": "Feature",
            "feature_value_name": "Feature Value Name",
            "feature_code_format": "Feature Code Format: HBG_xxx_xxxxx",
            "feature_value_format": "Feature Value Format: K-xxx-xxxxxx",
            "rule_tags": "Tags",
            "tech_doc": "Technical Doc",
            "edit_tags": "Edit Tags",
            "input_tags": "Enter tags (separate multiple tags with commas)",
            "select_tech_doc": "Select Technical Document",
            "word_files": "Word Documents",
            "tech_doc_added_success": "Technical document added successfully",
            "import_tech_doc": "Import Technical Doc",
            "open_tech_doc_error": "Failed to open technical document, please make sure the file exists and is accessible",
            "adjust_logic": "Adjust Logic",
            "on": "On",
            "add": "add",
            "from": "From",
            "change_quantity_of": "Change quantity of",
            "to": "to",
            "change_price": "Change price",
            "insert": "Insert",
            "error_multiple_tuning_logic": "An expression can only contain one tuning logic",
            "error_incomplete_on_add": "Please enter complete ON ADD values",
            "error_incomplete_from_delete": "Please enter complete FROM DELETE values",
            "error_incomplete_change_quantity": "Please enter complete CHANGE QUANTITY values",
            "error_invalid_price_format": "Price must start with + or - followed by numbers",
            "export_and_clear_success": "Rules exported successfully, temporary data has been cleared",
            "search_and_filter": "Search and Filter",
            "logic_type_filter": "Logic Type",
            "all_logics": "All Logics",
            "bom_logic": "BOM Logic",
            "tuning_logic": "Tuning Logic",
            "logic_status_filter": "Logic Status",
            "all_statuses": "All Statuses",
            "search_condition": "Search Condition",
            "search_effect": "Search Effect",
            "search_tags": "Search Tags",
            "clear_all_filters": "Clear All Filters",
            "search_bom_code": "Search BOM Code",
            "search_feature_or_k": "Search Feature Code (HBG-number) or Feature Value (K-number)",
            "code_not_found": "No matching feature code or value found",
            "export_descriptions": "Export Descriptions",
            "descriptions_exported_successfully": "Descriptions exported successfully",
            "export_descriptions_error": "Failed to export descriptions",
            "description": "Description"
        })
        
        # 德文翻译
        self._translations["de"].update({
            "app_title": "ZK Logik-Editor",
            "confirm": "Bestätigen",
            "cancel": "Abbrechen",
            "error": "Fehler",
            "warning": "Warnung",
            "info": "Information",
            "menu_file": "Datei",
            "menu_view": "Ansicht",
            "menu_help": "Hilfe",
            "import_config": "Konfiguration importieren",
            "import_bom": "BOM importieren",
            "logic_library": "Logik-Bibliothek",
            "language": "Sprache",
            "theme": "Thema",
            "view_log": "Log anzeigen",
            "about": "Über",
            "exit": "Beenden",
            "panels_title": "ZK Logik-Editor",
            "config_panel_title": "Konfiguration",
            "logic_panel_title": "Logik-Editor",
            "bom_panel_title": "BOM-Verwaltung",
            "tools": "Werkzeugleiste",
            "refresh": "Aktualisieren",
            "clear": "Löschen",
            "save": "Speichern",
            "logic_operators": "Logische Operatoren",
            "brackets": "Klammern",
            "rule_status": "Regel-Status",
            "enabled": "Aktiviert",
            "disabled": "Deaktiviert",
            "testing": "Test",
            "expression": "Ausdruck",
            "saved_rules": "Gespeicherte Regeln",
            "config_tree": "Konfigurations-Baum",
            "bom_tree": "BOM-Baum",
            "search": "Suche",
            "rules": "Regeln",
            "rule_id": "Regel-ID",
            "rule_type": "Regel-Typ",
            "condition": "Auswahlausdruck",
            "effect": "Wirkungsausdruck",
            "status": "Status",
            "light_theme": "Helles Thema",
            "dark_theme": "Dunkles Thema",
            "ready": "Bereit",
            "copy_code": "Code kopieren",
            "copy_item": "Element kopieren",
            "edit": "Bearbeiten",
            "delete": "Löschen",
            "select_excel_file": "Excel-Datei auswählen",
            "select_bom_file": "BOM-Datei auswählen",
            "excel_files": "Excel-Dateien",
            "all_files": "Alle Dateien",
            "confirm_exit": "Beenden bestätigen",
            "confirm_exit_message": "Möchten Sie das Programm wirklich beenden?",
            "excel_imported_successfully": "Excel-Datei erfolgreich importiert",
            "bom_imported_successfully": "BOM-Datei erfolgreich importiert",
            "excel_import_error": "Fehler beim Importieren der Excel-Datei",
            "bom_import_error": "Fehler beim Importieren der BOM-Datei",
            "refresh_tree_error": "Fehler beim Aktualisieren des Baums",
            "open_log_error": "Fehler beim Öffnen der Log-Datei",
            "theme_dialog_title": "Thema auswählen",
            "theme_dialog_header": "Bitte wählen Sie ein Thema",
            "refresh_tree": "Baum aktualisieren",
            "clear_expression": "Ausdruck löschen",
            "save_rule": "Regel speichern",
            "delete_last": "Letztes löschen",
            "clear_all": "Alles löschen",
            "error_must_start_with_k": "Ausdruck muss mit K-Code beginnen",
            "error_bom_before_implication": "BOM-Code kann nicht vor → eingefügt werden",
            "error_k_after_implication": "K-Code kann nicht nach → eingefügt werden",
            "error_invalid_operator_sequence": "K-Codes müssen durch AND, OR, AND NOT oder OR NOT verbunden sein",
            "error_invalid_bracket": "Ungültige Klammerverwendung",
            "error_invalid_token": "Ungültige Eingabe",
            "empty_expression": "Ausdruck darf nicht leer sein",
            "missing_implication_operator": "Fehlender Implikationsoperator →",
            "empty_left_expression": "Linker Ausdruck vor → darf nicht leer sein",
            "empty_right_expression": "Rechter Ausdruck nach → darf nicht leer sein",
            "left_expression_error": "Fehler im linken Ausdruck vor →",
            "right_expression_error": "Fehler im rechten Ausdruck nach →",
            "not_operator_error": "Ungültige Verwendung des NOT-Operators",
            "parentheses_mismatch": "Nicht übereinstimmende Klammern",
            "invalid_bool_expression": "Ungültiger boolescher Ausdruck",
            "error_consecutive_codes": "Codes können nicht direkt aufeinander folgen, es müssen Operatoren dazwischen verwendet werden",
            "expression_ends_with_operator": "Ausdruck darf nicht mit einem Operator enden",
            "invalid_first_token": "Ausdruck muss mit linker Klammer, NOT oder K-Code beginnen",
            "invalid_token_after_operator": "Operator muss von linker Klammer, NOT oder Variable gefolgt werden",
            "invalid_token_after_not": "NOT muss von linker Klammer oder Variable gefolgt werden",
            "invalid_token_after_left_parenthesis": "Linke Klammer muss von linker Klammer, NOT oder Variable gefolgt werden",
            "invalid_token_after_right_parenthesis": "Rechte Klammer muss von rechter Klammer, AND, OR oder → gefolgt werden",
            "invalid_token_after_k_code": "K-Code muss von rechter Klammer, AND, OR oder → gefolgt werden",
            "invalid_token_after_implication": "→ muss von linker Klammer, NOT oder BOM-Code gefolgt werden",
            "invalid_token_after_bom_code": "BOM-Code muss von rechter Klammer, AND oder OR gefolgt werden",
            "invalid_expression_state": "Ungültiger Ausdruckszustand",
            "error_consecutive_operators": "Operatoren können nicht aufeinanderfolgend verwendet werden",
            "load_last_config_confirm": "Letzte Konfigurationsdatei laden?",
            "load_last_bom_confirm": "Letzte BOM-Datei laden?",
            "load_last_config_error": "Fehler beim Laden der letzten Konfigurationsdatei",
            "load_last_bom_error": "Fehler beim Laden der letzten BOM-Datei",
            "update_display_error": "Fehler beim Aktualisieren der Anzeige",
            "success": "Erfolg",
            "success_title": "Erfolg",
            "import_config_success": "Konfigurationsdatei erfolgreich importiert",
            "import_bom_success": "BOM-Datei erfolgreich importiert",
            "error_title": "Fehler",
            "warning_title": "Warnung",
            "confirm_title": "Bestätigen",
            "error_invalid_before_k": "Vor einem K-Code muss eine linke Klammer, AND, OR oder NOT stehen",
            "error_invalid_before_bom": "Vor einem BOM-Code muss →, eine linke Klammer, AND, OR oder NOT stehen",
            "error_invalid_first_input": "Ausdruck muss mit K-Code, linker Klammer oder NOT beginnen",
            "error_invalid_sequence": "Ungültige Eingabereihenfolge, bitte prüfen Sie die Regeln für logische Ausdrücke",
            "error_unmatched_parentheses": "Nicht übereinstimmende Klammern, bitte überprüfen Sie die Anzahl der linken und rechten Klammern",
            "error_consecutive_not": "NOT-Operatoren können nicht aufeinanderfolgend verwendet werden",
            "error_consecutive_left_parentheses": "Linke Klammern müssen durch anderen Inhalt getrennt sein",
            "error_consecutive_right_parentheses": "Rechte Klammern müssen durch anderen Inhalt getrennt sein",
            "error_empty_parentheses": "Klammern dürfen nicht leer sein",
            "error_parentheses_after_not": "Rechte Klammer kann nicht direkt nach NOT folgen",
            "error_operator_before_right_parenthesis": "Rechte Klammer kann nicht nach einem Operator folgen",
            "error_missing_left_parenthesis": "Fehlende entsprechende linke Klammer",
            "error_missing_right_parenthesis": "Fehlende entsprechende rechte Klammer",
            "error_invalid_after_operator": "Nach einem Operator muss ein K-Code, BOM-Code, NOT oder eine linke Klammer folgen",
            "error_invalid_before_operator": "Vor einem Operator muss ein K-Code, BOM-Code oder eine rechte Klammer stehen",
            "error_invalid_after_not": "Nach NOT muss ein K-Code, BOM-Code oder eine linke Klammer folgen",
            "error_invalid_after_left_parenthesis": "Nach einer linken Klammer muss ein K-Code, NOT oder eine linke Klammer folgen",
            "error_invalid_before_right_parenthesis": "Vor einer rechten Klammer muss ein K-Code, BOM-Code oder eine rechte Klammer stehen",
            "error_invalid_before_implication": "Vor dem Implikationsoperator (→) muss ein K-Code oder eine rechte Klammer stehen",
            "error_multiple_implications": "Der Ausdruck darf nur einen Implikationsoperator (→) enthalten",
            "error_invalid_after_variable": "Nach einer Variable muss eine rechte Klammer, AND, OR oder → folgen",
            "error_validation_failed": "Ausdrucksvalidierung fehlgeschlagen, bitte überprüfen Sie Ihre Eingabe",
            "error_invalid_before_left_parenthesis": "Vor einer linken Klammer muss AND, OR, NOT oder → stehen",
            "error_invalid_before_right_parenthesis": "Vor einer rechten Klammer muss ein K-Code, BOM-Code oder eine rechte Klammer stehen",
            "error_invalid_before_operator": "Vor einem Operator muss ein K-Code, BOM-Code oder eine rechte Klammer stehen",
            "error_invalid_before_implication": "Vor dem Implikationsoperator (→) muss ein K-Code oder eine rechte Klammer stehen",
            "error_invalid_before_not": "Vor NOT darf keine Variable oder rechte Klammer stehen",
            "error_implication_at_start": "Der Ausdruck darf nicht mit dem Implikationsoperator (→) beginnen",
            "error_empty_expression": "Ausdruck darf nicht leer sein",
            "error_missing_implication": "Bitte geben Sie zuerst einen logischen Grundausdruck mit → Symbol ein",
            "error_invalid_expression_format": "Ungültiges Ausdrucksformat",
            "error_saving_rule": "Fehler beim Speichern der Regel",
            "rule_saved_successfully": "Regel erfolgreich gespeichert",
            "edit_rule": "Logikregel bearbeiten",
            "edit_rule_condition": "Auswahlausdruck",
            "edit_rule_effect": "Wirkungsausdruck",
            "edit_rule_status": "Regelstatus",
            "export_logic_rules": "BOM-Logikregeln exportieren",
            "load_last_rules_confirm": "Nicht exportierte BOM-Logikregeln aus der letzten Sitzung erkannt, laden?",
            "unsaved_rules_exit_confirm": "Es gibt nicht exportierte BOM-Logikregeln, möchten Sie wirklich beenden?",
            "export_rules_success": "BOM-Logikregeln erfolgreich exportiert",
            "export_rules_error": "Fehler beim Exportieren der BOM-Logikregeln",
            "select_export_file": "Exportdatei-Speicherort auswählen",
            "json_files": "JSON-Dateien",
            "rules_deleted": "Nicht gespeicherte BOM-Logikregeln wurden gelöscht",
            "import_logic_rules": "BOM-Logikregeln importieren",
            "select_import_file": "Importdatei auswählen",
            "import_rules_success": "BOM-Logikregeln erfolgreich importiert",
            "import_rules_error": "Fehler beim Importieren der BOM-Logikregeln",
            "unsaved_rules_import_confirm": "Nicht exportierte BOM-Logikregeln erkannt, beim Importieren neuer Regeln werden die aktuellen Regeln gelöscht, fortfahren?",
            "unsaved_rules_warning": "Es gibt nicht exportierte BOM-Logikregeln",
            "temp_rules_loaded": "Temporär gespeicherte BOM-Logikregeln geladen",
            "temp_rules_not_found": "Keine temporär gespeicherten BOM-Logikregeln gefunden",
            "temp_rules_load_error": "Fehler beim Laden der temporär gespeicherten BOM-Logikregeln",
            "temp_rules_save_success": "BOM-Logikregeln temporär gespeichert",
            "temp_rules_save_error": "Fehler beim temporären Speichern der BOM-Logikregeln",
            "confirm_delete_rule": "Möchten Sie diese Regel wirklich löschen?",
            "feature_value": "Merkmalwert",
            "feature_code": "Merkmale",
            "feature_value_name": "Merkmalwertname",
            "feature_code_format": "Merkmalcode Format: HBG_xxx_xxxxx",
            "feature_value_format": "Merkmalwert Format: K-xxx-xxxxxx",
            "rule_tags": "Tags",
            "tech_doc": "Technische Dok",
            "edit_tags": "Tags bearbeiten",
            "input_tags": "Tags eingeben (mehrere Tags durch Kommas trennen)",
            "select_tech_doc": "Technische Dokumentation auswählen",
            "word_files": "Word-Dokumente",
            "tech_doc_added_success": "Technische Dokumentation erfolgreich hinzugefügt",
            "import_tech_doc": "Technische Dokumentation importieren",
            "open_tech_doc_error": "Fehler beim Öffnen der technischen Dokumentation. Stellen Sie sicher, dass die Datei existiert und zugänglich ist",
            "adjust_logic": "Logik anpassen",
            "on": "Bei",
            "add": "hinzufügen",
            "from": "Von",
            "change_quantity_of": "Menge ändern von",
            "to": "zu",
            "change_price": "Preis ändern",
            "insert": "Einfügen",
            "error_multiple_tuning_logic": "Ein Ausdruck kann nur eine Abstimmungslogik enthalten",
            "error_incomplete_on_add": "Bitte geben Sie vollständige ON ADD Werte ein",
            "error_incomplete_from_delete": "Bitte geben Sie vollständige FROM DELETE Werte ein",
            "error_incomplete_change_quantity": "Bitte geben Sie vollständige CHANGE QUANTITY Werte ein",
            "error_invalid_price_format": "Der Preis muss mit + oder - beginnen, gefolgt von Zahlen",
            "export_and_clear_success": "Regeln erfolgreich exportiert, temporäre Daten wurden gelöscht",
            "search_and_filter": "Suchen und Filtern",
            "logic_type_filter": "Logiktyp",
            "all_logics": "Alle Logiken",
            "bom_logic": "BOM-Logik",
            "tuning_logic": "Anpassungslogik",
            "logic_status_filter": "Logikstatus",
            "all_statuses": "Alle Status",
            "search_condition": "Bedingung suchen",
            "search_effect": "Wirkung suchen",
            "search_tags": "Tags suchen",
            "clear_all_filters": "Alle Filter löschen",
            "search_bom_code": "BOM-Code suchen",
            "search_feature_or_k": "Merkmalcode (HBG-Nr.) oder Merkmalwert (K-Nr.) suchen",
            "code_not_found": "Kein passender Merkmalcode oder Merkmalwert gefunden",
            "export_descriptions": "Beschreibungen exportieren",
            "descriptions_exported_successfully": "Beschreibungen erfolgreich exportiert",
            "export_descriptions_error": "Fehler beim Exportieren der Beschreibungen",
            "description": "Beschreibung"
        })
        
    def add_callback(self, callback):
        """添加语言变化时的回调函数
        
        Args:
            callback: 回调函数
        """
        try:
            if callback not in self._callbacks:
                self._callbacks.append(callback)
        except Exception as e:
            print(f"添加回调函数时出错: {str(e)}")
            
    def remove_callback(self, callback):
        """移除回调函数
        
        Args:
            callback: 要移除的回调函数
        """
        try:
            if callback in self._callbacks:
                self._callbacks.remove(callback)
        except Exception as e:
            print(f"移除回调函数时出错: {str(e)}")
            
    def set_language(self, lang_code: str) -> None:
        """设置当前语言
        
        Args:
            lang_code: 语言代码
        """
        try:
            if lang_code in ["zh", "en", "de"] and lang_code != self._current_language:
                self._current_language = lang_code
                config_manager.set_app_config("language", lang_code)
                # 调用所有回调函数
                for callback in self._callbacks[:]:  # 创建副本以避免迭代时修改
                    try:
                        callback()
                    except Exception as e:
                        print(f"回调函数执行出错: {str(e)}")
                        # 如果回调函数不再有效，从列表中移除
                        self._callbacks.remove(callback)
        except Exception as e:
            print(f"设置语言时出错: {str(e)}")
    
    def get_text(self, key: str) -> str:
        """获取指定键的翻译文本
        
        Args:
            key: 翻译键
            
        Returns:
            str: 翻译文本
        """
        try:
            return self._translations[self._current_language].get(key, key)
        except Exception as e:
            print(f"获取翻译文本时出错: {str(e)}")
            return key
    
    def get_current_language(self) -> str:
        """获取当前语言代码
        
        Returns:
            str: 当前语言代码
        """
        return self._current_language

# 创建全局语言管理器实例
language_manager = LanguageManager()